version: '3.8'

services:
  golang-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-be
    hostname: golang-be
    networks:
      - mynet
    ports:
      - 8080:8080
    volumes:
      - ./:/app

networks:
  mynet:
    driver: bridge
